version: '3.3'

services:
  django:
    environment:
      API_KEY: ${API_KEY}
    image: xb0t/django-weather-app
    volumes:
      - /home/ubuntu/projects/Django-Weather-App/sqlite_data:/code/db.sqlite3
    ports:
      -  "8000"

networks:
  default:
    name: yash_network
    external: true
