version: '3.3'

services:
  django:
    environment:
      API_KEY: ${API_KEY}
    image: xb0t/django-weather-app
    volumes:
      - sqlite_data:/code
    ports:
      -  "32773:8000"
volumes:
  sqlite_data:
  
networks:
  default:
    name: yash_network
    external: true
