# Generated by Django 4.1.3 on 2022-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10, verbose_name='City Name')),
            ],
            options={
                'verbose_name_plural': 'City',
                'ordering': ['city'],
            },
        ),
    ]
